INSERT INTO kraje VALUES('PL', 'Polska', 'zloty');
INSERT INTO kraje VALUES('DE', 'Niemcy', 'euro');
INSERT INTO kraje VALUES('CZ', 'Czechy', 'euro');
INSERT INTO kraje VALUES('RU', 'Rosja', 'rubel');
INSERT INTO kraje VALUES('FR', 'Francja', 'euro');
INSERT INTO kraje VALUES('NL', 'Niderlandy', 'euro');
INSERT INTO kraje VALUES('LT', 'Litwa', '');
INSERT INTO kraje VALUES('BE', 'Belgia', 'euro');
INSERT INTO kraje VALUES('AT', 'Austria', 'euro');
INSERT INTO kraje VALUES('HU', 'Wegry', 'forint');
INSERT INTO kraje VALUES('IT', 'Wlochy', 'euro');
INSERT INTO kraje VALUES('BY', 'Bialorus', null);
commit;

INSERT INTO kategorie(Nazwa) VALUES('nocleg');
INSERT INTO kategorie(Nazwa) VALUES('plazowanie');
INSERT INTO kategorie(Nazwa) VALUES('zwiedzanie');
INSERT INTO kategorie(Nazwa) VALUES('gastronomia');
INSERT INTO kategorie(Nazwa) VALUES('rejsy');
INSERT INTO kategorie(Nazwa) VALUES('wedrowanie');
INSERT INTO kategorie(Nazwa) VALUES('natura');
commit;

INSERT INTO miejsca(Kod_kraju, Nazwa, Szerokosc_geograficzna, Dlugosc_geograficzna, Opis) VALUES('PL', 'Warszawa', '52�13''47''''N','021�00''42''''E', '');
INSERT INTO miejsca(Kod_kraju, Nazwa, Szerokosc_geograficzna, Dlugosc_geograficzna, Opis) VALUES('PL', 'Trojmiasto', '54�26''30''''N','018�33''36''''E', null);
INSERT INTO miejsca(Kod_kraju, Nazwa, Szerokosc_geograficzna, Dlugosc_geograficzna, Opis) VALUES('PL', 'Bialowieski Park Narodowy', '52�29''00''''N','023�31''00''''E', null);
INSERT INTO miejsca(Kod_kraju, Nazwa, Szerokosc_geograficzna, Dlugosc_geograficzna, Opis) VALUES('PL', 'Zakopane', '49�17''58''''N','019�57''02''''E', null);
INSERT INTO miejsca(Kod_kraju, Nazwa, Szerokosc_geograficzna, Dlugosc_geograficzna, Opis) VALUES('PL', 'Poznan', '52�25''00''''N','016�58''00''''E', null);
INSERT INTO miejsca(Kod_kraju, Nazwa, Szerokosc_geograficzna, Dlugosc_geograficzna, Opis) VALUES('PL', 'Suwalszczyzna', '54�06''04''''N','022�55''57''''E', null);
INSERT INTO miejsca(Kod_kraju, Nazwa, Szerokosc_geograficzna, Dlugosc_geograficzna, Opis) VALUES('RU', 'Moskwa', '55�45''00''''N','037�37''50''''E', null);
INSERT INTO miejsca(Kod_kraju, Nazwa, Szerokosc_geograficzna, Dlugosc_geograficzna, Opis) VALUES('RU', 'Smolensk', '54�46''54''''N','032�02''24''''E', null);
INSERT INTO miejsca(Kod_kraju, Nazwa, Szerokosc_geograficzna, Dlugosc_geograficzna, Opis) VALUES('BY', 'Minsk', '53�53''59''''N','027�34''00''''E', null);
INSERT INTO miejsca(Kod_kraju, Nazwa, Szerokosc_geograficzna, Dlugosc_geograficzna, Opis) VALUES('LT', 'Wilno', '54�41''20''''N','025�16''47''''E', null);
INSERT INTO miejsca(Kod_kraju, Nazwa, Szerokosc_geograficzna, Dlugosc_geograficzna, Opis) VALUES('PL', 'Suwalki', '54�06''42''''N','022�55''51''''E', null);
INSERT INTO miejsca(Kod_kraju, Nazwa, Szerokosc_geograficzna, Dlugosc_geograficzna, Opis) VALUES('PL', 'Bialystok', '53�07''59''''N','023�09''51''''E', null);
INSERT INTO miejsca(Kod_kraju, Nazwa, Szerokosc_geograficzna, Dlugosc_geograficzna, Opis) VALUES('PL', 'Lodz', '51�45''00''''N','019�28''00''''E', null);
INSERT INTO miejsca(Kod_kraju, Nazwa, Szerokosc_geograficzna, Dlugosc_geograficzna, Opis) VALUES('PL', 'Wroclaw', '51�06''00''''N','017�01''59''''E', null);
INSERT INTO miejsca(Kod_kraju, Nazwa, Szerokosc_geograficzna, Dlugosc_geograficzna, Opis) VALUES('CZ', 'Praga', '50�05''16''''N','014�25''14''''E', null);
INSERT INTO miejsca(Kod_kraju, Nazwa, Szerokosc_geograficzna, Dlugosc_geograficzna, Opis) VALUES('DE', 'Norymberga', null, null, null);
INSERT INTO miejsca(Kod_kraju, Nazwa, Szerokosc_geograficzna, Dlugosc_geograficzna, Opis) VALUES('DE', 'Stuttgart', null, null, null);
INSERT INTO miejsca(Kod_kraju, Nazwa, Szerokosc_geograficzna, Dlugosc_geograficzna, Opis) VALUES('FR', 'Strasburg', '48�35''02''''N','007�44''43''''E', null);
INSERT INTO miejsca(Kod_kraju, Nazwa, Szerokosc_geograficzna, Dlugosc_geograficzna, Opis) VALUES('FR', 'Pary�', '48�51''12''''N','002�20''55''''E', null);
INSERT INTO miejsca(Kod_kraju, Nazwa, Szerokosc_geograficzna, Dlugosc_geograficzna, Opis) VALUES('PL', 'Sandomierz', null,null, null);
INSERT INTO miejsca(Kod_kraju, Nazwa, Szerokosc_geograficzna, Dlugosc_geograficzna, Opis) VALUES('PL', 'Katowice', null,null, null);
INSERT INTO miejsca(Kod_kraju, Nazwa, Szerokosc_geograficzna, Dlugosc_geograficzna, Opis) VALUES('PL', 'Krakow', '50�03''41''''N','019�56''11''''E', null);
commit;

INSERT INTO kategorie_miejsc VALUES(1, 1);
INSERT INTO kategorie_miejsc VALUES(1, 3);
INSERT INTO kategorie_miejsc VALUES(1, 4);

INSERT INTO kategorie_miejsc VALUES(2, 1);
INSERT INTO kategorie_miejsc VALUES(2, 2);
INSERT INTO kategorie_miejsc VALUES(2, 3);
INSERT INTO kategorie_miejsc VALUES(2, 4);
INSERT INTO kategorie_miejsc VALUES(2, 5);

INSERT INTO kategorie_miejsc VALUES(3, 1);
INSERT INTO kategorie_miejsc VALUES(3, 4);
INSERT INTO kategorie_miejsc VALUES(3, 6);
INSERT INTO kategorie_miejsc VALUES(3, 7);

INSERT INTO kategorie_miejsc VALUES(4, 1);
INSERT INTO kategorie_miejsc VALUES(4, 3);
INSERT INTO kategorie_miejsc VALUES(4, 4);
INSERT INTO kategorie_miejsc VALUES(4, 6);

INSERT INTO kategorie_miejsc VALUES(5, 1);
INSERT INTO kategorie_miejsc VALUES(5, 3);
INSERT INTO kategorie_miejsc VALUES(5, 4);

INSERT INTO kategorie_miejsc VALUES(6, 1);
INSERT INTO kategorie_miejsc VALUES(6, 3);
INSERT INTO kategorie_miejsc VALUES(6, 4);
INSERT INTO kategorie_miejsc VALUES(6, 6);
INSERT INTO kategorie_miejsc VALUES(6, 7);

INSERT INTO kategorie_miejsc VALUES(7, 1);
INSERT INTO kategorie_miejsc VALUES(7, 3);
INSERT INTO kategorie_miejsc VALUES(7, 4);
INSERT INTO kategorie_miejsc VALUES(8, 1);
INSERT INTO kategorie_miejsc VALUES(8, 3);
INSERT INTO kategorie_miejsc VALUES(8, 4);
INSERT INTO kategorie_miejsc VALUES(9, 1);
INSERT INTO kategorie_miejsc VALUES(9, 3);
INSERT INTO kategorie_miejsc VALUES(9, 4);
INSERT INTO kategorie_miejsc VALUES(10, 1);
INSERT INTO kategorie_miejsc VALUES(10, 3);
INSERT INTO kategorie_miejsc VALUES(10, 4);
INSERT INTO kategorie_miejsc VALUES(11, 1);
INSERT INTO kategorie_miejsc VALUES(11, 3);
INSERT INTO kategorie_miejsc VALUES(11, 4);
INSERT INTO kategorie_miejsc VALUES(12, 1);
INSERT INTO kategorie_miejsc VALUES(12, 3);
INSERT INTO kategorie_miejsc VALUES(12, 4);
INSERT INTO kategorie_miejsc VALUES(13, 1);
INSERT INTO kategorie_miejsc VALUES(13, 3);
INSERT INTO kategorie_miejsc VALUES(13, 4);
INSERT INTO kategorie_miejsc VALUES(14, 1);
INSERT INTO kategorie_miejsc VALUES(14, 3);
INSERT INTO kategorie_miejsc VALUES(14, 4);
INSERT INTO kategorie_miejsc VALUES(15, 1);
INSERT INTO kategorie_miejsc VALUES(15, 3);
INSERT INTO kategorie_miejsc VALUES(15, 4);
INSERT INTO kategorie_miejsc VALUES(16, 1);
INSERT INTO kategorie_miejsc VALUES(16, 4);
INSERT INTO kategorie_miejsc VALUES(17, 1);
INSERT INTO kategorie_miejsc VALUES(17, 3);
INSERT INTO kategorie_miejsc VALUES(17, 4);
INSERT INTO kategorie_miejsc VALUES(18, 1);
INSERT INTO kategorie_miejsc VALUES(18, 3);
INSERT INTO kategorie_miejsc VALUES(19, 1);
INSERT INTO kategorie_miejsc VALUES(19, 3);
INSERT INTO kategorie_miejsc VALUES(19, 4);
INSERT INTO kategorie_miejsc VALUES(19, 5);
INSERT INTO kategorie_miejsc VALUES(20, 1);
INSERT INTO kategorie_miejsc VALUES(20, 3);
INSERT INTO kategorie_miejsc VALUES(20, 4);
INSERT INTO kategorie_miejsc VALUES(21, 1);
INSERT INTO kategorie_miejsc VALUES(21, 3);
INSERT INTO kategorie_miejsc VALUES(21, 4);
INSERT INTO kategorie_miejsc VALUES(22, 1);
INSERT INTO kategorie_miejsc VALUES(22, 3);
INSERT INTO kategorie_miejsc VALUES(22, 4);
commit;

INSERT INTO podroze(Nazwa, Data_rozpoczecia, Data_zakonczenia, Opis) VALUES('Roznorodnosc Polski', TO_DATE('15-06-2022', 'DD-MM-YYYY'), TO_DATE('15-07-2022', 'DD-MM-YYYY'), null);
INSERT INTO podroze(Nazwa, Data_rozpoczecia, Data_zakonczenia, Opis) VALUES('Wzdluz Europy', null, null, null);
INSERT INTO podroze(Nazwa, Data_rozpoczecia, Data_zakonczenia, Opis) VALUES('Miasta poludniowej Polski', TO_DATE('20-07-2021', 'DD-MM-YYYY'), TO_DATE('10-08-2021', 'DD-MM-YYYY'), null);
commit;

INSERT INTO miejsca_podrozy VALUES(1, 2, 1);
INSERT INTO miejsca_podrozy VALUES(1, 6, 2);
INSERT INTO miejsca_podrozy VALUES(1, 3, 3);
INSERT INTO miejsca_podrozy VALUES(1, 1, 4);
INSERT INTO miejsca_podrozy VALUES(1, 22, 5);
INSERT INTO miejsca_podrozy VALUES(1, 4, 6);

INSERT INTO miejsca_podrozy VALUES(2, 7, 1);
INSERT INTO miejsca_podrozy VALUES(2, 8, 2);
INSERT INTO miejsca_podrozy VALUES(2, 9, 3);
INSERT INTO miejsca_podrozy VALUES(2, 10, 4);
INSERT INTO miejsca_podrozy VALUES(2, 11, 5);
INSERT INTO miejsca_podrozy VALUES(2, 12, 6);
INSERT INTO miejsca_podrozy VALUES(2, 1, 7);
INSERT INTO miejsca_podrozy VALUES(2, 13, 8);
INSERT INTO miejsca_podrozy VALUES(2, 14, 9);
INSERT INTO miejsca_podrozy VALUES(2, 15, 10);
INSERT INTO miejsca_podrozy VALUES(2, 16, 11);
INSERT INTO miejsca_podrozy VALUES(2, 17, 12);
INSERT INTO miejsca_podrozy VALUES(2, 18, 13);
INSERT INTO miejsca_podrozy VALUES(2, 19, 14);

INSERT INTO miejsca_podrozy VALUES(3, 14, 1);
INSERT INTO miejsca_podrozy VALUES(3, 21, 2);
INSERT INTO miejsca_podrozy VALUES(3, 22, 3);
INSERT INTO miejsca_podrozy VALUES(3, 20, 4);
commit;